### ISSUE TITLE
Why Electron?

### ISSUE THREAD

**Issue by Stiffi136** [theoarav/Payday3ChallengeViewer#2]
I appreciate the work you've put in to write this project. Although I'm wondering why you chose Electron instead of a website? I guess more people would rather use a website instead of downloading a program.

**Comment by theoarav** [comment]
I wanted to try Electron and since it was a simple personal project originally it suited me well to try it. No more reason than that, I had someone contact me by MP saying they took the code inside `src/renderer` and made a personal website with it.

On top of that since this program use the starbreeze account I felt like most people would rather trust an app with sources rather than a website to not store informations...

And I think with CORS I would have needed an API to make the calls to Starbreeze instead of making them using the web browser directly.

Hope this answers your question :)

**Comment by Stiffi136** [comment]
Thanks for the quick reply. I understand your reason now, and I completely forgot CORS.

Thanks again for this awesome tool :)
