### ISSUE TITLE
Challenge issues

### ISSUE THREAD

**Issue by SirHazza** [theoarav/Payday3ChallengeViewer#20]
### App bugs:

- DIRTY ICE: REPEAT OFFENDER QUIET & LETHAL VIII - Isn't shown when filter 'heist: dirty ice' is applied

### Challenges I recommend you mark as bugged:

- GOLD & SHARKE: FUNCTIONAL TRAINING - Unable to complete, see [here](https://www.reddit.com/r/paydaytheheist/comments/16yeckr/bugged_challenge_functional_training/) and [here](https://www.reddit.com/r/paydaytheheist/comments/16oisg2/payday_3_challenge_question/)

and
- ROAD RAGE: REPEAT OFFENDER ROWDY & HARSH VII
- ROAD RAGE: REPEAT OFFENDER ROWDY & LETHAL VIII - Both have the wrong completion requirement set as evidenced by the descriptions, devs accidently set it to the IP number

**Comment by DudiVok** [comment]
Those are some definitely good to know informations, thank you for telling us about them.

Currently we flag each challenge as bugged dynamically based on a simple factor. If the progress value of it equals or is higher than the requirement (say you have a 1/1 progression on a challenge) and is not considered to be completed, we flag it as bugged. The Functional Training challenge is kind of a unique case by itself since its not that its not unlocking, it is basically not registering that you even did it.

We are currently reworking the whole app before continuing to make new features. We could however make a static array of said challenges so that they wouldnt receive values from the API but rather from our code.
