### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by dennisrijsdijk** [theoarav/Payday3ChallengeViewer#23]
I was looking to contribute, fork or otherwise use the code in this repository, but noticed it has no license attached. 
As per [The Opensource Guide](https://opensource.guide/legal/#are-public-github-projects-open-source), a repository is not opensource if it doesn't have a license attached. 
Please consider adding a permissive FOSS license to the project to allow code usage in other projects.

**Comment by DudiVok** [comment]
Hi! Thank you for reaching out. 

Unfortunately all of the devs on the project lost interest in developing the app further, making the repository basically an archive (about which i'll try to contact the creator of the repo). 

Nonetheless, I've added a GPL 3.0 licesing to it, that should let you legally do whatever you wish with the code in the repository, but as I stated, the repo is basically an archive now, so you can just create forks freely, and you don't really need to make PRs afterwards, since most likely they won't really be accepted.
